# Generated by Django 4.2.4 on 2023-08-23 13:58

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMethodCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=20, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('alias', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'm_error_api_method_call',
            },
        ),
        migrations.CreateModel(
            name='ApiSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('alias', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'm_error_api_section',
            },
        ),
        migrations.CreateModel(
            name='ErrorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=15, unique=True)),
                ('user_message', models.TextField(null=True)),
                ('ignore', models.BooleanField()),
                ('priority', django_mysql.models.EnumField(choices=[('default', 'default'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='default')),
                ('error_type', django_mysql.models.EnumField(choices=[('default', 'default'), ('error', 'error'), ('warning', 'warning'), ('information', 'information')], default='default')),
                ('documentation', models.TextField()),
                ('alias', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'm_error_list',
            },
        ),
        migrations.CreateModel(
            name='ErrorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('alias', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'm_error_name',
            },
        ),
        migrations.CreateModel(
            name='FrontendErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_code', models.CharField(max_length=10)),
                ('error_datetime', models.DateTimeField(auto_now_add=True)),
                ('error_description', models.TextField(null=True)),
                ('error_type', models.CharField(max_length=100)),
                ('priority', django_mysql.models.EnumField(choices=[('default', 'default'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='default')),
                ('resolution_status', django_mysql.models.EnumField(choices=[('not_resolved', 'not_resolved'), ('being_resolved', 'being_resolved'), ('resolved', 'resolved'), ('for_later', 'for_later')], default='not_resolved')),
                ('screen', models.CharField(max_length=100, null=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'frontend_errors',
            },
        ),
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=200, null=True)),
                ('debug_log', models.TextField(null=True)),
                ('request_body', models.JSONField(null=True)),
                ('extra_debug_information', models.JSONField(null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(max_length=200, null=True)),
                ('origin_ip', models.CharField(max_length=100, null=True)),
                ('resolved', models.BooleanField(default=0)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('alias', models.CharField(max_length=255, null=True, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='error_handling.apisection')),
            ],
            options={
                'db_table': 'm_error_api',
                'unique_together': {('code', 'section')},
            },
        ),
    ]
